name: Deploy TeamSpeak 3 Server

on:
  push:
    branches: [ master ]

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Deploy image
        run: |
          export RELEASE=$(grep "TS3_VERSION=" Dockerfile | sed 's|^.*=||g' |awk '{print $1}')
          docker pull polinux/teamspeak:stage
          docker tag polinux/teamspeak:stage polinux/teamspeak:${RELEASE}
          docker tag polinux/teamspeak:stage polinux/teamspeak:latest
          docker login  -u ${{ secrets.DOCKER_HUB_USER }} -p ${{ secrets.DOCKER_HUB_PASS }}
          docker push polinux/teamspeak:${RELEASE}
          docker push polinux/teamspeak:latest